### ISSUE TITLE
blacklist

### ISSUE THREAD

**Issue by vaniron** [hsyyid/EssentialCmds#101]
Banned items are removed only after taking them into hand. Would it be possible to remove them immediately on pickup or prevent pickup?

**Comment by kinggoesgaming** [comment]
I prefer remove on pickup +1

**Comment by vaniron** [comment]
How is the progress on this? Really needed to get rig of some bugged modded stuff.

**Comment by hsyyid** [comment]
@aglarcz Looking at it... it is coded. It seems like the pickup event is not working.

**Comment by hsyyid** [comment]
Closed via https://github.com/SpongePowered/SpongeCommon/commit/89825d743e3cc97b9c3c451b3a1169c2ccb2a046

**Comment by hsyyid** [comment]
That's actually a Sponge bug, please report it there
