### ISSUE TITLE
SpongeForge 1377 Issues

### ISSUE THREAD

**Issue by KumaGetsu** [hsyyid/EssentialCmds#105]
1377 causing issues with teleporting

Not able to copy text of the errors in chat mouse-over info so here's 2 screenshots of the issues.

setLocation
http://puu.sh/pcnxi/57a1cbf9ca.png

setTransform
http://puu.sh/pcnzw/24bbe28286.png

**Comment by hsyyid** [comment]
Okay thanks for letting me know, will get to it

**Comment by hsyyid** [comment]
Fixed in v8.1.7
