### ISSUE TITLE
EssentialCmds doesn't work on SpongeForge 1.9.4 singleplayer

### ISSUE THREAD

**Issue by Aaron1011** [hsyyid/EssentialCmds#109]
[This listener](https://github.com/hsyyid/EssentialCmds/blob/master/src/main/java/io/github/hsyyid/essentialcmds/EssentialCmds.java#L187) relies on the server being available (through `EssLogger`). However, in 1.9.4 (clientside), the server is not always available. Specifically, it only becomes available while in a singleplayer world, as opposed to on the main screen.

**Comment by hsyyid** [comment]
Okay, thanks for the report, will fix ASAP

**Comment by hsyyid** [comment]
Fixed via eb67bf9dcba574bf16548f58397268c246411ad4
