### ISSUE TITLE
Players who are banned still show "disconnect" messages

### ISSUE THREAD

**Issue by inklit** [hsyyid/EssentialCmds#110]
When setting a disconnect message, players who are banned still show disconnect messages, but no join messages.

**Comment by hsyyid** [comment]
This could be Sponge related, or it could be I am receiving the event to early.

**Comment by inklit** [comment]
I should mention that I am using minecraft:ban and not /ban, although I think they do roughly the same thing.

**Comment by inklit** [comment]
This is a Sponge bug, will report it there sometime later.
