### ISSUE TITLE
StackOverflowException with /sethome

### ISSUE THREAD

**Issue by kinggoesgaming** [hsyyid/EssentialCmds#113]
log: http://pastebin.com/R8Bg0wzR

Reported by StonerBud_

steps to reproduce:
- run `/sethome <name>

Error shows if ingame or in console. No permissions plugin. All players are op.

Minecraft: v8.1.12
Sponge: 1.10.2-2002-5.0.0-BETA-1539
EssentialCMDs: v8.1.12
Forge: 12.18.0.2006

**Comment by kinggoesgaming** [comment]
issue on SF side i think SpongePowered/SpongeForge/issues/737

**Comment by MarkTwoFive** [comment]
Related issue got closed. Does this still happen to you?

**Comment by kinggoesgaming** [comment]
@hsyyid is this still valid otherwise I can close this.
