### ISSUE TITLE
teleport issue

### ISSUE THREAD

**Issue by vaniron** [hsyyid/EssentialCmds#119]
Players  got problems after teleporting when they see only sky/nothing and must relogin. This happens for tp, home, warps etc. No errors at all. I am using latest plugin build with latest sponge. 
Any ideas for this?

**Comment by hsyyid** [comment]
What sponge are you on?

**Comment by vaniron** [comment]
1.8.9 build 1563

**Comment by MarkTwoFive** [comment]
I just used all of those commands while messing around with Teleport-Events in the SpongeAPI.
Didn't notice anything similar.

Do you have further information on your setup ? Installed mods/plugins, configuration, etc ?

**Comment by vaniron** [comment]
All can be seen here: 
https://timings.aikar.co/v2/?id=bb8aa6cddb9541ad930c711ee30e6b1a&section=plugins

**Comment by MarkTwoFive** [comment]
Okay, I may try to reproduce this if I've time today, but first: 
You did try to reproduce the issue with only EssentialCmds installed ?
