### ISSUE TITLE
Warp command does not allow console sender

### ISSUE THREAD

**Issue by bitonality** [hsyyid/EssentialCmds#120]
I can't warp players via command block because the WarpExecutor checks to see if the command sender is an instanceof Player. I don't believe that this is an intended behaviour, but if it is, I would strongly advise you to rethink the functionality of warps.

[Code in Warp Executor Class](https://github.com/hsyyid/EssentialCmds/blob/cb08d7371907a6c754ea71d4375a3da3011b8b05/src/main/java/io/github/hsyyid/essentialcmds/cmdexecutors/WarpExecutor.java#L60)

This same check exists in SetWarpExecutor class and ListWarpExecutor class.

Thanks - Would love to get this fixed

**Comment by MarkTwoFive** [comment]
This is also the same with /world tp
