### ISSUE TITLE
Exception when player join

### ISSUE THREAD

**Issue by ghost** [hsyyid/EssentialCmds#128]
sometimes get http://pastebin.com/V21DLQwj

**Comment by hsyyid** [comment]
Turn off save inventory. It does not work, and I have said many times to leave it disabled.

**Comment by ghost** [comment]
How? I see no word "inventory" in the main config file...

**Comment by hsyyid** [comment]
@hunter688 in the world config..

**Comment by ghost** [comment]
oh i see, looks like this config should be disabled by default or add modded dimesions automatically...

**Comment by ghost** [comment]
thanks
