### ISSUE TITLE
Make EssentialCmds modular

### ISSUE THREAD

**Issue by kinggoesgaming** [hsyyid/EssentialCmds#13]
Currently EssentialCmds is one big bunch of all the features bundled into one big bunch. It is much better if it is broken down into modules...
- [ ] Break the gradle project into a structure like this:

```
EssentialCmdsCore (API plugin)
+- Transportation (For tp, homes, warp, spawn and other transport stuff)
+- Communication (For any means of communication ie chat, /msg etc etc)
+- Punishment (Mutes, kicks, bans, etc)
...
```
- [ ] Break the plugin down into the  corresponding gradle structure

This is what i came up with so would love to get feedback on it before I actually do it

**Comment by hsyyid** [comment]
I approve of this structure - it makes more sense as users may or may not want specific parts of the plugin rather than the whole thing.

**Comment by kinggoesgaming** [comment]
ok I just want some input from the users of the plugin too... linked them to here on forums

**Comment by hsyyid** [comment]
@kinggoesgaming Yep I saw :+1:

**Comment by kinggoesgaming** [comment]
add modules label to the issue

**Comment by kinggoesgaming** [comment]
Blocked by #18

**Comment by kinggoesgaming** [comment]
Closing this as Nucleus does this now
