### ISSUE TITLE
Could you offer more configerable options?

### ISSUE THREAD

**Issue by 5igm** [hsyyid/EssentialCmds#130]
My server uses different language, and I want to change the reminder to another language, but there are only four options in message part. Could you offer more options for that? In addition, I am confused for 
# Message sent to everyone when a player joins.

```
login=""
```

What is the difference between the option above and the one below?
# Message sent to a player when they join the server.

```
join="
```

**Comment by 5igm** [comment]
One more suggestion:
Could the plugin add the object I hold to the blacklist automatically? Since Minecraft deleted ID number for each item, as players it is pretty hard to find out the real name of mod items.

**Comment by hsyyid** [comment]
First one is sent to everyone when someone joins. Second one is sent to the player who joins.

For example, login by default is <player> has joined the server. For the other one, there is no default, but most servers have some sort of welcome message there.

**Comment by hsyyid** [comment]
"players it is pretty hard to find out the real name of mod items."

Not very true... you can go on a website to get the IDs... http://minecraft-ids.grahamedgecombe.com/

"Could you offer more options for language"

No. Nucleus will have localization support meaning it will support many languages. If you'd like that feature, I suggest moving to it.

**Comment by 5igm** [comment]
Thanks for your suggestion and explaination.
