### ISSUE TITLE
Crash when using EssentialCmds with PermissionManager

### ISSUE THREAD

**Issue by knackrack615** [hsyyid/EssentialCmds#134]
Whenever i use those 2 together the server crashes

I'm not really sure if this is an EssentialCmds issue or a PermissionManager issue

(Theres also a forestry error but i don't really see how forestry can interfere with EssentialCmds)

[Error Log](https://scrgrb.xyz/t/2016-08-09_14-07-02.txt)
[Full Server Log](https://scrgrb.xyz/t/2016-08-09_14-06-10.txt)

**Comment by hsyyid** [comment]
Permission manager
