### ISSUE TITLE
Not launching the server

### ISSUE THREAD

**Issue by KyleStewart95** [hsyyid/EssentialCmds#135]
After I try to launch the server with EssentialsCMDS it just crashes.
I am using EssentialCmds-1.8.9-8.1.14-universal.
It says the following:

10.08 14:49:21 [Server] main/WARN [FML]: The coremod chylex.javacheck.Java8CheckerCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
10.08 14:49:21 [Server] main/INFO [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8.9-1722-3.1.0-BETA-1136.jar
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
10.08 14:49:21 [Server] main/INFO [mixin]: SpongePowered MIXIN Subsystem Version=0.4.19 Source=file:/mods/spongeforge-1.8.9-1722-3.1.0-BETA-1136.jar Env=SERVER
10.08 14:49:21 [Server] main/INFO [mixin]: Compatibility level set to JAVA_8
10.08 14:49:21 [Server] main/INFO [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
10.08 14:49:21 [Server] main/INFO [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
10.08 14:49:21 [Server] main/INFO [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
10.08 14:49:21 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
10.08 14:49:22 [Server] main/ERROR [FML]: FML appears to be missing any signature data. This is not a good thing
10.08 14:49:22 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
10.08 14:49:22 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
10.08 14:49:22 [Server] main/INFO [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
10.08 14:49:23 [Server] main/INFO [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@737a135b
10.08 14:49:23 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
10.08 14:49:23 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
10.08 14:49:23 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
10.08 14:49:23 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
10.08 14:49:23 [Server] main/INFO [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
10.08 14:49:26 [Server] main/INFO [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
10.08 14:49:29 [Server] Server thread/INFO Starting minecraft server version 1.8.9
10.08 14:49:29 [Server] Server thread/INFO [FML]: MinecraftForge v11.15.1.1722 Initialized
10.08 14:49:29 [Server] Server thread/INFO [FML]: Replaced 204 ore recipies
10.08 14:49:31 [Server] Server thread/INFO [FML]: Found 0 mods from the command line. Injecting into mod discoverer
10.08 14:49:31 [Server] Server thread/INFO [FML]: Searching /mods for mods
10.08 14:49:32 [Server] Server thread/WARN [FML]: Zip file EssentialCmds-1.8.9-8.1.14-universal.jar failed to read properly, it will be ignored
10.08 14:49:32 [Server] INFO java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
10.08 14:49:32 [Server] INFO at org.spongepowered.mod.plugin.SpongeModPluginContainer.bindMetadata(SpongeModPluginContainer.java:139) ~[SpongeModPluginContainer.class:1.8.9-1722-3.1.0-BETA-1136]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:85) [JarDiscoverer.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:134) [ModDiscoverer.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:363) [Loader.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488) [Loader.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
10.08 14:49:32 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) [FMLCommonHandler.class:?]
10.08 14:49:32 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) [ko.class:?]
10.08 14:49:32 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
10.08 14:49:32 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
10.08 14:49:33 [Server] Server thread/INFO [FML]: Forge Mod Loader has identified 8 mods to load
10.08 14:49:33 [Server] Server thread/ERROR Encountered an unexpected exception
10.08 14:49:33 [Server] INFO java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
10.08 14:49:33 [Server] INFO at org.spongepowered.mod.plugin.SpongeModPluginContainer.getSortingRules(SpongeModPluginContainer.java:174) ~[SpongeModPluginContainer.class:1.8.9-1722-3.1.0-BETA-1136]
10.08 14:49:33 [Server] INFO at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:303) ~[Loader.class:?]
10.08 14:49:33 [Server] INFO at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:492) ~[Loader.class:?]
10.08 14:49:33 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
10.08 14:49:33 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
10.08 14:49:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) ~[ko.class:?]
10.08 14:49:33 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
10.08 14:49:33 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
10.08 14:49:33 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2016-08-10_14.49.33-server.txt
10.08 14:49:33 [Server] Server thread/WARN [FML]: Can't revert to frozen GameData state without freezing first.
10.08 14:49:33 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
10.08 14:49:33 [Server] Server thread/INFO [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
10.08 14:49:34 [Multicraft] Server shut down
10.08 14:49:34 [Multicraft] Server stopped

I hope this may help fix it if you have any idea can you tell me.

**Comment by kinggoesgaming** [comment]
Mind if you use pastebin.com? Near impossible to read the log

**Comment by KyleStewart95** [comment]
Hope this helps 
http://pastebin.com/eqS40mjr

**Comment by MarkTwoFive** [comment]
`Zip file EssentialCmds-1.8.9-8.1.14-universal.jar failed to read properly, it will be ignored`

Also: The log mentions a crash log `crash-2016-08-10_19.53.27-server.txt`  that has been written. It may be helpful if you could post it too.

**Comment by KyleStewart95** [comment]
This is the crash log hope it helps

http://pastebin.com/jXGNmvjE

**Comment by kinggoesgaming** [comment]
Seems like version mismatch

**Comment by MarkTwoFive** [comment]
Yep, but also seems like this hasn't to do with EssentialCmds.

FYI: Try using these 2 versions:
Forge: 11.15.1.1902
SpongeForge: 1890-4.1.0-BETA- 1395 

These two work for a server I maintain.

Note: Your current Sponge build `1722-3.1.0-BETA-1136` is deprecated since Sponge API version 3.X is no longer maintained.

**Comment by KyleStewart95** [comment]
This is what I am getting now if it helps I am running Pixelmon server with the following installed and working:
Evs-Ivs-1.8.9-4.1.0-universal.jar
forge-1.8.9-11.15.1.1902-1.8.9-installer.jar (I do not know if that what you ment MarkL4YG)
NoDownfall-v1.0.1.jar
PixelAuction-1.8.9-1.0.3-universal.jar
Pixelmon-1.8.9-4.2.7-universal.jar
spongeforge-1.8.9-1722-3.1.0-BETA-1136.jar
TotalEconomy-v1.4.1.jar
worldedit-forge-mc1.8.9-6.1.1.jar
EssentialCmds v8.1.14

What I am getting from ther server now :
http://pastebin.com/ucjpEhTL

**Comment by hsyyid** [comment]
Youre using an extremely old sponge forge...
