### ISSUE TITLE
RTP checks for safe blocks until server crashes.

### ISSUE THREAD

**Issue by tenten8401** [hsyyid/EssentialCmds#137]
Using /rtp in a void dimension will lock up the server until watchdog shuts it down. Please fix this! Also, possibly have it teleport you to a configurable world when /rtp is called.

**Comment by ryantheleach** [comment]
http://pastebin.com/jah9yNP4 I think this is related. I thought originally that Sponge might be at fault. but if what you are saying is true tenten, then something needs to change.

**Comment by ryantheleach** [comment]
I think I may have duplicated this issue here: https://github.com/hsyyid/EssentialCmds/issues/140

PR to hopefully reduce the number of chunks loaded. Should probably add the failure cases.
https://github.com/hsyyid/EssentialCmds/pull/141

**Comment by hsyyid** [comment]
Thanks @ryantheleach for fixing this
