### ISSUE TITLE
Hello latest ecmds build still crashing on latest sponge vanilla build...

### ISSUE THREAD

**Issue by WillPowerCraft** [hsyyid/EssentialCmds#152]
Hello! how about build for 1.11?

Now i tried test load server with 1.11 sponge and 1.10.2 ecmds and look that consol log:

> D:\MCS\Test
> 
>  build\server>java -Xms1G -Xmx1G -jar spongevanilla-1.11-6.0.0-BETA-170.jar
> [18:09:37 INFO] [Sponge]: Initializing Sponge...
> [18:09:37 INFO] [Sponge]: De-obfuscation mappings are provided by MCP (http://www.modcoderpack.com)
> [18:09:38 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.6.1 Source=file:/D:/MCS/test build/server/spongevanilla-1.11-6.0.0-BETA-170.jar Env=UNKNOWN
> [18:09:38 INFO] [mixin]: Compatibility level set to JAVA_8
> [18:09:38 INFO] [Sponge]: Searching for plugins...
> **[18:09:38 ERROR] [LaunchWrapper]: Unable to launch**
> java.lang.IllegalArgumentException: id must match pattern [a-z][a-z0-9-_]{0,63}
>         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[minecraft_server.1.11.jar:?]
>         at org.spongepowered.plugin.meta.PluginMetadata.setId(PluginMetadata.java:103) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.plugin.meta.gson.ModMetadataAdapter.read(ModMetadataAdapter.java:91) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.plugin.meta.gson.ModMetadataCollectionAdapter.read(ModMetadataCollectionAdapter.java:51) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.plugin.meta.gson.ModMetadataCollectionAdapter.read(ModMetadataCollectionAdapter.java:36) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:256) ~[minecraft_server.1.11.jar:?]
>         at org.spongepowered.plugin.meta.McModInfo.read(McModInfo.java:117) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.plugin.PluginScanner.scanJar(PluginScanner.java:229) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.plugin.PluginScanner.scanDirectory(PluginScanner.java:173) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.plugin.VanillaLaunchPluginManager.findPlugins(VanillaLaunchPluginManager.java:66) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.VanillaServerTweaker.searchPlugins(VanillaServerTweaker.java:161) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.VanillaServerTweaker.injectIntoClassLoader(VanillaServerTweaker.java:84) ~[spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
>         at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
>         at org.spongepowered.server.launch.VanillaServerMain.main(VanillaServerMain.java:118) [spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
>         at org.spongepowered.server.launch.VersionCheckingMain.main(VersionCheckingMain.java:38) [spongevanilla-1.11-6.0.0-BETA-170.jar:1.11-6.0.0-BETA-170]
> 
> D:\MCS\Test build\server>pause
> press any key to continue. . .
>

**Comment by kinggoesgaming** [comment]
He need a to change the ID for the plugin 

I will open a PR for this in a bit

**Comment by kinggoesgaming** [comment]
@BabelSolea you can try this version till he merges #154 https://www.dropbox.com/s/rql6vprz6voqyng/EssentialCmds-1.8.9-8.1.14-universal.jar?dl=0
