### ISSUE TITLE
sqlite is not a viable option

### ISSUE THREAD

**Issue by MoeBoy76** [hsyyid/EssentialCmds#3]
my server host has informed me that sqlite cannot be installed due to some limitations so would it be possible to be able to use MySQL or h2 as alternatives? Minecraft server hosts tend to offer free MySQL and h2 is MPL/EPL and allowed to be distributed

**Comment by hsyyid** [comment]
Okay. I'll look into it! :smile:

**Comment by hsyyid** [comment]
Done, it now has MySQL support. When you open up the config after starting, there will be an option called mysql, under which there will be an option use, which will be false. Set that to true, restart your server and more options will appear. Fill in the info for your MySQL Database, and it should work fine. :smile:
