### ISSUE TITLE
Fly Broken (Survival)

### ISSUE THREAD

**Issue by viveleroi** [hsyyid/EssentialCmds#36]
When using `tp` or `warp` commands with fly on, we're unable to fly. Calling `/fly` disables it. `/fly` again will enable it, and fly works as expected.

**Comment by Darktilldawn** [comment]
I don't have this issue on 6.9c Version of Eseentials. Try updating first

**Comment by viveleroi** [comment]
This is still occurring, v7.2e, sponge 1138. It's happening across multiple servers with very different plugins, and one server where essentials is the only plugin loaded. It's 100% consistent.

**Comment by hsyyid** [comment]
`/fly` broke recently, I am looking into the cause - it may be SpongeCommon related.

**Comment by kinggoesgaming** [comment]
Does this issue still happen? @hsyyid 

If it is, a simple solution may be that before teleporting, check if the player is flying and store that value and teleport. after teleport apply the value.

**Comment by hsyyid** [comment]
@kinggoesgaming The entire `/fly` command doesn't appear to work anymore..

**Comment by kinggoesgaming** [comment]
@hsyyid ok thats weird.. AFAIK Flying is using Data API unless I am mistaken. If it is then it is possible that FlyData could be broken...

**Comment by 12awsomeman34** [comment]
? I don't have any issue with `/fly`, teleportation or regardless. Maybe something to do with the way it handles FlyData on specific setups?
SpongeForge 1145
EssentialCmds 7.4

Edit:
I was flying in creative, and I performed `/fly`. It stated that it disabled flying yet I could keep flying upwards (not downwards). Then I was kicked for flying is not enabled on this server and the server crashed. Likely an issue with SpongeCommon.

**Comment by hsyyid** [comment]
@12AwsomeMan34 I've tried it out again and while in survival on SpongeForge, couldn't fly despite my capabilities being updated via SpongeCommon.

[SpongeCommon Issue](https://github.com/SpongePowered/SpongeCommon/issues/494)

**Comment by 12awsomeman34** [comment]
@hsyyid I can fly in survival :/
http://i.imgur.com/qkk9HIP.jpg

SpongeForge 1151
EssentialCmds 7.4c

**Comment by kinggoesgaming** [comment]
Hooray for fly hacks #derps
