### ISSUE TITLE
Jail command

### ISSUE THREAD

**Issue by klemenmeglic** [hsyyid/EssentialCmds#37]
Part of jail command is not working.
Command /jail <player> <cell> is working normally, but
Command /unjail <player> throws an error. I hve attached console output if it helps.

[Unjail_Fault.txt](https://github.com/hsyyid/EssentialCmds/files/93492/Unjail_Fault.txt)

**Comment by hsyyid** [comment]
Try setting your spawn again.

**Comment by klemenmeglic** [comment]
Sorry didnt know :)  Now that this is a question...

If I place a command block with command inside, I get an error inside command block "You must be a in-game player to do /time!. Is that another issue or did I miss anything?

you get the same error if you try command from console...

**Comment by hsyyid** [comment]
I'll fix it soon
