### ISSUE TITLE
Error while executing command with /gamemode

### ISSUE THREAD

**Issue by 12awsomeman34** [hsyyid/EssentialCmds#38]
This doesn't seem to have been reported afaik, so here it is:

Using EssentialCmds version 6.9c (current latest).
Using SpongeForge version 1060 (spongeforge-1.8.9-1694-3.1.0-BETA-1060).
Using forge version 1694 (forge-1.8.9-11.15.0.1694-universal).

Whenever I run the `/gm` command and attempt to specify anything other than creative, I get an error. `/gm 0` works, however `/gm s` or `/gm survival` does not. Likewise, `/gm adventure` throws an error, but `/gm 2` does not. Same for spectator.

Although, when I run `/gm 1`, `/gm c` or `/gm creative`, it works without issue.
I've also tried specifying the player argument, same error. I've even tried restarting the server, issue persists. Here is the error I'm sure will be useful: http://pastebin.com/0ATASJcF

**Comment by hsyyid** [comment]
I'll check it out
