### ISSUE TITLE
Add Configurable Home/Teleportation Timer Option(s)

### ISSUE THREAD

**Issue by jules552** [hsyyid/EssentialCmds#40]
You should add:

the possibility to configure a timer for /home command. (the same for the /polis hq)

**Comment by hiperpoo** [comment]
This is something I would like to see as well. Like essentials a configurable timer for /home /tpa /tpahere unless you have a specific permission, or a /tpo command. Also hsyyid or HassanS6000 thanks a bunch for implementing an essentials esk plugin for sponge!
