### ISSUE TITLE
Multiworld Requires allow-nether=true

### ISSUE THREAD

**Issue by paleym** [hsyyid/EssentialCmds#42]
EssentialCmds 7.2d
FoxCore-v0.6.2-70-SNAPSHOT-server
FoxGuard-v0.16.1-206-SNAPSHOT
spongeforge-1.8.9-1722-3.1.0-BETA-1110

Attempted to make a flat, overworld, creative, peaceful world and the server said no because 'allow-nether' was set to false?  I don't care for nether, but I need to have it enabled to make overworld-type worlds?

**Comment by hsyyid** [comment]
In your `server.properties`, there is an option called `allow-nether`, set this to true.
