### ISSUE TITLE
Limits on number of homes

### ISSUE THREAD

**Issue by paleym** [hsyyid/EssentialCmds#47]
Would be a nice feature to be able to set limits on the number of homes using nodes and the config like

essentialcmds.homes.<groupname>

and then have an area in the config for defining the number of homes for each tag

**Comment by kinggoesgaming** [comment]
technically it is possible but might mean an overhaul to the permissions for homes.

**Comment by paleym** [comment]
Not critical or anything, just thought it would be nice for my adventure server if we could set limits based on groups or something.

**Comment by hsyyid** [comment]
Limits on numbers of homes are possible.

Example using PEX:

`/pex group [group name] option homes [number of homes allowed]`

**Comment by kinggoesgaming** [comment]
never heard of PEX what is it :wink:
