### ISSUE TITLE
Updatifier compatibility broken

### ISSUE THREAD

**Issue by Flibio** [hsyyid/EssentialCmds#52]
The build.gradle file has some code in it that prevents EssentialCmds from working with Updatifier.

[View file here](https://github.com/hsyyid/EssentialCmds/blob/master/build.gradle#L93)

`project.version + getGitHash()` does not equal the exact tag that is found on GitHub. You should change it to `project.version`. It is preventing Updatifier from getting the tag from GitHub.

**Comment by kinggoesgaming** [comment]
Mm I think can get to this in about hour and fix it since I introduced it

**Comment by hsyyid** [comment]
@kinggoesgaming I'll fix it

**Comment by kinggoesgaming** [comment]
I am working on it rn :)

**Comment by hsyyid** [comment]
@kinggoesgaming kk

**Comment by liach** [comment]
I should say Updatifier checks tags from https://github.com/hsyyid/EssentialCmds/releases, and compare current release's date and the latest release's date on GitHub to see whether it is up to date.
