### ISSUE TITLE
Social Spy's colors and design

### ISSUE THREAD

**Issue by WoofingtonVonBarkshire** [hsyyid/EssentialCmds#58]
Socialspy works okay, except for a few issues. The first one is that when I send a message with socialspy enabled, I get two identical lines back, and the same with receiving, making it look something like this: http://puu.sh/n8t9o/fd80237429.png . This can get spammy with a /msg conversation really quickly, causing minor annoyance.

The second issue is that self-sent messages look exactly the same, except for the names, as messages sent by other players. This causes me to momentarily mistake someone else's conversation for my own, which is rather annoying. In the old Socialspy, things were much nicer; I could quickly differentiate someone else's conversation and mine without even thinking. Both of these issues could be fixed with some different color schemes, maybe some grays for socialspy messages, and the same colors for regular messages.

Thanks, and cheers.

**Comment by hsyyid** [comment]
Thanks for the suggestions! Will work on this soon.
