### ISSUE TITLE
Punctuation and special characters in /msg 

### ISSUE THREAD

**Issue by Ollie2000** [hsyyid/EssentialCmds#61]
so far I've only come across ", '. and \ not being usable in private messages and I was wondering why. If it is unintentional then can we get it fixed?

**Comment by hsyyid** [comment]
What do you mean by not usable? What happens when `\` or `,` is in the message?

**Comment by hsyyid** [comment]
Okay I tested. It appears that only this slash doesn't work: `\` it's most likely related to how Sponge handles arguments parsing.

**Comment by Ollie2000** [comment]
Sorry, was asleep. the charaters `"` `'` `\` didn't work. I thought I made it clear, apparently I didn't. Hope this clears it up.
