### ISSUE TITLE
/list shows me in every rank I inherit

### ISSUE THREAD

**Issue by paleym** [hsyyid/EssentialCmds#68]
Using PEX, as 'Owner', inheriting Admin, which inherits Mod, etc...

I show up as every rank in /list.

![2016-02-22_08 30 15](https://cloud.githubusercontent.com/assets/5383960/13222815/f1b18dc0-d93e-11e5-819f-69a4cc9e429d.png)

**Comment by hsyyid** [comment]
Fixed in 88d56657b9ef58f582e3108e74545475b977900a
