### ISSUE TITLE
/setspawn /spawn yaw point to south

### ISSUE THREAD

**Issue by ghost** [hsyyid/EssentialCmds#74]
When do /setspawn  and then /spawn  yaw set to south, looks like not saved what I want using /setspawn.

Also pitch looks like not saved.

**Comment by hsyyid** [comment]
Send me your `spawn.conf` via [PasteBin](http://pastebin.com)

**Comment by ghost** [comment]
http://pastebin.com/GDYhs3tr

**Comment by ghost** [comment]
another http://pastebin.com/dcixKJ7w

version 7.8b, spongeforge 1193

**Comment by hsyyid** [comment]
I have been testing this out locally, can you confirm this is still an issue?

**Comment by ghost** [comment]
version 7.8c, spongeforge 1195, issue still persist

**Comment by ghost** [comment]
7.8d, spongeforge 1207, issue still persist

**Comment by ghost** [comment]
I added some debug code to Utils.java getSpawn() and looks like problem is here: https://github.com/hsyyid/EssentialCmds/blob/master/src/main/java/io/github/hsyyid/essentialcmds/utils/Utils.java#L1142

Its wrongly detect if transform is in the config.

My config:
http://pastebin.com/XuW0QKT0

Debug patch:
http://pastebin.com/aXtY0xLv

Instead of "SPAWN PITCH" in the console I see "SPAWN"

**Comment by ghost** [comment]
I think found problem - typo - instead of _warpsConfig_ must be **spawnConfig** on this line:
https://github.com/hsyyid/EssentialCmds/blob/master/src/main/java/io/github/hsyyid/essentialcmds/utils/Utils.java#L1142

**Comment by ghost** [comment]
patch: http://pastebin.com/MwsqJYtb

Tested and fixed this issue.

**Comment by hsyyid** [comment]
@hunter688 thanks! I'll push a fix today

**Comment by ghost** [comment]
not fixed in 7.9 :(
