### ISSUE TITLE
teleport issue with sponge 1190

### ISSUE THREAD

**Issue by ghost** [hsyyid/EssentialCmds#75]
http://pastebin.com/nmmvjvXB

maybe api 4.1.x

when remove plugin can /tp nickname without problem

**Comment by hsyyid** [comment]
That's actually a SpongeAPI bug. Maybe open the issue there, but I already told some of their devs.

**Comment by 12awsomeman34** [comment]
The issue is open on the SpongeAPI:
https://github.com/SpongePowered/SpongeAPI/issues/1131
Follow developments there.
