### ISSUE TITLE
AFK Issue

### ISSUE THREAD

**Issue by KumaGetsu** [hsyyid/EssentialCmds#78]
Server is on the latest version 7.9b and players are being set as afk very quickly, even though the afk time is set to 30000.

On top of this issue, I'd like an addition to the config to disable AFK system.

**Comment by hsyyid** [comment]
You're sure this is an issue? 

Your AFK timer is set to 30 seconds... so do you mean quicker than 30 seconds?

**Comment by KumaGetsu** [comment]
Yes, they will have turned AFK as soon as they login... it doesn't seem to show up as an issue though when I set it to 900000.

**Comment by hsyyid** [comment]
AFK as soon as they login

ah... this is a bug... I'll look into it today.
