### ISSUE TITLE
PositionOutOfBoundsException

### ISSUE THREAD

**Issue by KumaGetsu** [hsyyid/EssentialCmds#81]
When logging into game while having left with GameMode 1

http://paste.ubuntu.com/15562960/

**Comment by hsyyid** [comment]
Seems like a bug with safelogin. I am looking into it now.

**Comment by hsyyid** [comment]
It was caused by an issue in the TeleportHelper, fixed in https://github.com/SpongePowered/SpongeCommon/pull/740
