### ISSUE TITLE
gamemode persisting

### ISSUE THREAD

**Issue by ghost** [hsyyid/EssentialCmds#83]
When set /gm 1 in the overworld, and teleport to another dimension (command, portal), gm 1 not persist, after teleport is set to gm 0

Will be possible set gamemode persist?

**Comment by hsyyid** [comment]
Gamemode does that so it updates based on the world you're switching to - it gets its default gamemode, and updates yours.

**Comment by ghost** [comment]
Many years with essentials on bukkit/spigot/cauldron when set gamemode 1 in some dimension and then teleport to another still have gamemode 1 not the default.

**Comment by ghost** [comment]
looks like duplicate of #59
