### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by KumaGetsu** [hsyyid/EssentialCmds#88]
Tried to type "&bhttp://pokemc.com" in chat and it gave this fatal error.
http://paste.ubuntu.com/15725508/

Putting a space in between "&b" and the link doesn't cause the fatal error.

**Comment by hsyyid** [comment]
Ok I'll look into it

**Comment by kinggoesgaming** [comment]
it is mostly how TextSerializer handles & symbol... it would nice to get an opinion from the sponge devs @hsyyid

**Comment by kinggoesgaming** [comment]
@hsyyid might be fixable by using regex to detect urls and color codes preceding them and adding space automatically

**Comment by KumaGetsu** [comment]
This was fixed in a recent version.
