### ISSUE TITLE
Use sponge standards for permission names

### ISSUE THREAD

**Issue by jeffreykog** [hsyyid/EssentialCmds#9]
Currently this plugin does not obey the sponge standards to permission names.

For example, a permission used by this plugin `vanish.use` should be changed to `spongeessentialcmds.command.vanish` or `spongeessentialcmds.command.vanish.use`

Something like `spongeessentialcmds.vanish.use` will suffice as well. At least include the plugin name

**Comment by hsyyid** [comment]
I'm not sure how users would react to me changing all the permissions when most of them have been actively using my plugin.

**Comment by jeffreykog** [comment]
I know. It's a difficult thing to fix now that the plugin is released and being used.

One thing you could do is add a warning in the logs and in the release notes to warn users that a change is upcoming. Then in a week or two you could release the permission rename.

If you warn your users early enough about the addition of the `spongeessentialcmds.` prefix, i hope the transition will go smooth. I know it's a difficult thing to do, but i hope you kinda agree with me in that it should be changed sometime in the future :smiley:

**Comment by hsyyid** [comment]
I do agree with you, and have been considering this for a long time. I'll give the users a heads up in the thread, and will add something in the log when the server is starting. Thanks for the advice!
